version: "3.8"

services:
  npm:
    image: 'jc21/nginx-proxy-manager:2'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - /home/ubuntu/npm/data:/data
      - /home/ubuntu/npm/letsencrypt:/etc/letsencrypt

  wg-easy:
    environment:
      - WG_HOST=${VPN_ENDPOINT}
      - PASSWORD=${PASSWORD}
    image: weejewel/wg-easy:7-nightly
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - /home/ubuntu/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  openldap:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    container_name: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "${DOMAIN} Inc."
      LDAP_DOMAIN: "${DOMAIN_ENDPOINT}"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "${PASSWORD}"
      LDAP_CONFIG_PASSWORD: "${PASSWORD}"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /home/ubuntu/openldap/ldap:/var/lib/ldap
      - /home/ubuntu/openldap/slapd:/etc/ldap/slapd.d
      - /home/ubuntu/openldap/certs:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    domainname: "${DOMAIN_ENDPOINT}"
    hostname: "ldap-server"

  phpldapadmin:
    image: osixia/phpldapadmin:stable
    restart: unless-stopped
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.401.1-lts
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - /home/ubuntu/jenkins/home:/var/jenkins_home